# Generated by Django 3.2.17 on 2023-02-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Deparment',
            new_name='Department',
        ),
    ]
